# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
target 'BeautifyExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BeautifyExample

  target 'BeautifyExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'AgoraRtcEngine_iOS', '4.1.1'
   #pod 'Nama','~> 7.3.0'
   pod 'Masonry'
   pod 'SVProgressHUD'

end
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
    end
  end
end
