# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BeautifyExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BeautifyExample

  target 'BeautifyExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end
   pod 'AGMCapturer_iOS', '~> 1.3.1.0'
   pod 'AgoraRtcEngine_iOS', '~> 3.0.1.1'
   pod 'Nama', '~> 7.1.0'
   pod 'Masonry'

end
